### ISSUE TITLE
Repo help

### ISSUE THREAD

**Issue by khaoticdude** [isislab/Hack-Night#7]
Hello, 

Recently I discovered your GitHub repo, and I am having difficulty
following it. Some of the directories seem to be missing content. Can
you explain the best way to follow along?

Khaotic

**Comment by HockeyInJune** [comment]
Start with the main [README.md](https://github.com/isislab/Hack-Night/blob/master/README.md).  Watch the videos for each lecture and do the workshops.  There are no answer keys or guided exercises.  If anything specific is missing, let us know.
